
library(dplyr)


# 1 - load the data
data <- read.csv("../../../data/eda/live_class/Hospitality_Data.csv", header = TRUE)

head(data)
dim(data)


# 2 - get a table of counts for booking status
table(data$booking_status)

data %>% 
  group_by(booking_status) %>% 
  summarize(Count = length(booking_id)) %>% 
  as.data.frame()


# 3 - get a table of proportions for booking platform
table(data$booking_platform)
round(prop.table(table(data$booking_platform)) * 100, 2)

data %>% 
  group_by(booking_platform) %>% 
  summarize(Count = n()) %>% 
  mutate(Percentage = (Count / sum(Count)) * 100) %>%
  as.data.frame()


# 4 - get a table fo booking volume by day of week
data %>% 
  group_by(Day.Name) %>%
  summarize(Total_Bookings = n_distinct(booking_id)) %>%
  arrange(desc(Total_Bookings)) %>%
  as.data.frame()


# 5 - visualize the spread of revenue generated by each booking platform
boxplot(revenue_generated ~ booking_platform, data = data, col = "cadetblue", main = "Revenue Generated by Booking Platform")


# 6 - find the median rating given by the customers
data$ratings_given <- as.numeric(data$ratings_given)

min(data$ratings_given, na.rm = TRUE)
median(data$ratings_given, na.rm = TRUE)
max(data$ratings_given, na.rm = TRUE)


# 7 - find the median rating by room type
data %>%
  group_by(room_category) %>%
  summarise(Median_ratings = median(as.numeric(ratings_given), na.rm = TRUE)) %>%
  as.data.frame()








