---
title: "Exploratory Data Analysis"
author: "Jerry Kiely"
date: "`r Sys.Date()`"
output: 
  pdf_document:
    toc: true
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```







\newpage

# Descriptive Statistics

\vspace{1.5em}







## Measures of Central Tendency and Variation

\vspace{1.5em}





### Sources and Types of Data

\vspace{1.5em}



#### Sources of Data

\vspace{1.5em}

1. Primary Data

\vspace{1.5em}

* the data is collected by the investigator himself / herself for a specific purpose
* direct method of data collection
* eg. data collected for research through questionnaires, interviews

\vspace{1.5em}

2. Secondary Data

\vspace{1.5em}

* the data is collected by someone else, but being used by the investigator for some other purpose
* an indirect method of data collection
* eg. census data being used to study the impact of education on income

\vspace{1.5em}



#### Types of Data

\vspace{1.5em}

1. Structured Data

* information is stored with a high degree of organization
* contains qualitative data, quantitative data, or a mixture of both
* eg. data arranged in an excel file, in rows and columns

\vspace{1.5em}

2. Unstructured Data

\vspace{1.5em}

* information that either does not have a pre-defined data model and / or is not organized in a pre-defined manner
* eq. emails, tweets, blogs, etc.

\vspace{1.5em}





### Measurement Scales

\vspace{1.5em}

1. Nominal Scale

\vspace{1.5em}

* the placing of data into categories without any order or structure
* no numerical relationship between categories - even if numbers are used for representation
* eg. gender, nationality, language, region, etc.

\vspace{1.5em}

2. Ordinal Scale

\vspace{1.5em}

* the placing of data into categories such that the order of values is meaningful, but relative degree of difference is not known
* eg. ranking the features of a product on a scale of 1 to 5
* the Likert scale - psychometric scale commonly used in questionnaires

\vspace{1.5em}

| Highly Satisfied | Dissatisfied | Neutral      | Satisfied    | Highly Satisfied | 
|------------------|--------------|--------------|--------------|------------------|
|        1         |       2      |      3       |       4      |         5        |

\vspace{1.5em}

3. Interval Scale

\vspace{1.5em}

* numeric scale in which the order as well as the relative difference between values is known
* no "true zero"
* eg. temperature can be below $0^\circ C$ 

\vspace{1.5em}

4. Ratio Scale

\vspace{1.5em}

* numeric scale with an absolute "zero"
* addition, subtraction, multiplication, and division are all valid operations
* eg. height, weight age, etc. - always measured from $0$ to a maximum value

\vspace{1.5em}





### Measures of Central Tendency

\vspace{1.5em}

a.k.a. Measures of Central Location

\vspace{1.5em}

* a single value that describes a set of data by identifying the central position within that set of data

\vspace{1.5em}

The most commonly used measures of central tendency are: 

\vspace{1.5em}

* Mean
  * arithmetic mean, commonly known as average
  * sum of all values divided by the number of values 

\vspace{1.5em}

* Median
  * arrange N data elements in order
  * if N is odd take the middle value
  * if N is even take the average of the two middle values 

\vspace{1.5em}

* Mode
  * the most frequently occuring value in a data set 

\vspace{1.5em}

The mean, median, and mode are all valid measures of central tendency, but under different conditions, some 
measures are more appropriate than others. 

\vspace{1.5em}

It is recommended to report trimmed mean along with mean when outliers are present. Trimmed mean excludes
extreme data points from the calculation. Typically $5%$ of data from each end is excluded - which will 
give a robust estimate if the underlying distribution is symmetric.

\vspace{1.5em}

| Type of variable             | Best Measure |
|------------------------------|--------------|
| Nominal                      | Mode         |
| Ordinal                      | Median       |
| Interval / Ratio (symmetric) | Mean         |
| Interval / Ratio (skewed)    | Median       |

\vspace{1.5em}

* for a symmetric distribution the mean is appropriate - the mean is at the center
* for a skewed distribution the median is appropriate - the mean is generally not at the center

\vspace{1.5em}













\newpage
